### PR TITLE
fix coordinator leader proxy in druid console server

### LINKED ISSUE #16: npm install fails
I wonder which node version should be used to build the project.

For example if I use node v0.10.40 (npm v1.4.28) which is specified in package.json, I get:
```
> node-sass@3.2.0 install ...node_modules/node-sass
> node scripts/install.js


...node_modules/node-sass/node_modules/request/node_modules/hawk/node_modules/boom/lib/index.js:5
const Hoek = require('hoek');
^^^^^
SyntaxError: Use of const in strict mode.
```

If I use node  v9.2.0 (npm v5.5.1) I get:
```
> fsevents@0.2.1 install ...node_modules/watchify/node_modules/fsevents
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/fse/fsevents.o
In file included from ../fsevents.cc:6:
../../nan/nan.h:339:13: error: no member named 'New' in 'v8::String'
    return  _NAN_ERROR(v8::Exception::Error, errmsg);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
MacOS 10.12.6

### PR DESCRIPTION
**Pull request by clintropolis**
Druid coordinator leader API includes scheme after [this change](https://github.com/druid-io/druid/commit/2ecebb31731ddc9b1597dccaf57738359c5423ac#diff-2ed9a00e63ba80d914302e0f4b2a18b4R74). This fix handles that case instead of breaking and loading nothing.

Additionally: 
* fixed unit tests, run unit tests on PR via travis
* fixed build to work with recent versions of nodejs (tested with 6 and 8 lts versions) which should fix #16 
* updated npm dependencies, fixing issues related to migration (i.e. express 3.x to 4.x) 
* replaced bundled zookeeperLocator.js with updated [locators](https://github.com/metamx/locators) npm dependency, which has many fixes and should make the druid console server much more resilient in the face of network blips and zookeeper outages

### CODE REVIEW

**Comment by clintropolis** [comment]
2 of the tests are currently failing when I run them locally:
```
Chrome 63.0.3239 (Mac OS X 10.13.2) $hUtils processServers should break the list of servers into tiers and calculate tier summaries FAILED
	Expected $.tiers[0].resilience = 1.890655552464516 to equal 1.
	Expected $.tiers[1].resilience = 0.5480894015974194 to equal 0.
	    at UserContext.<anonymous> (/var/folders/ym/1t6nfv55205fhhv1rx_qxww40000gn/T/92b02c66740af11f5ac3da98ef02cdd0.browserify:12461:24)
```
and 
```
Chrome 63.0.3239 (Mac OS X 10.13.2) $hUtils resilience should calculate resilience properly FAILED
	Expected 1.9900000000000002 to equal 1.
	    at UserContext.<anonymous> (/var/folders/ym/1t6nfv55205fhhv1rx_qxww40000gn/T/92b02c66740af11f5ac3da98ef02cdd0.browserify:12755:40)
	Expected 1.0099999999999998 to equal 1.
	    at UserContext.<anonymous> (/var/folders/ym/1t6nfv55205fhhv1rx_qxww40000gn/T/92b02c66740af11f5ac3da98ef02cdd0.browserify:12757:40)
	Expected 0.9900000000000002 to equal 0.
	    at UserContext.<anonymous> (/var/folders/ym/1t6nfv55205fhhv1rx_qxww40000gn/T/92b02c66740af11f5ac3da98ef02cdd0.browserify:12759:40)
	Expected 9.9 to equal 9.
	    at UserContext.<anonymous> (/var/folders/ym/1t6nfv55205fhhv1rx_qxww40000gn/T/92b02c66740af11f5ac3da98ef02cdd0.browserify:12761:47)
```

However, the console itself appears to function correctly (did not test rule or config updates, just clicked around to make sure stuff loaded).

File: src/server/server.coffee [hunk 1]
```diff
@@ -4,21 +4,28 @@ request = require 'request'
...
+getZkDruidCoordinator = (req) -> "druid:#{req.params.cluster}:master"
+getZkDruidIndexer = (req) -> "druid:#{req.params.cluster}:indexer"
+getZkDruidBard = (req) -> "druid:#{req.params.cluster}:bard"
+
+getDruidLocator = (druidZkLocation) ->
+  zkDiscovery(druidZkLocation)()
 
-zkManager = null
-dns.resolve4 zookeeperSettings.hostname, (err, addresses) ->
+dns.resolve4 zkHostname, (err, addresses) ->
```
Comment (esevastyanov) [inline src/server/server.coffee]: is this dns-resolving only to validate `zkHostName`?

File: pom.xml [hunk 2]
```diff
@@ -116,8 +116,8 @@
                 <goal>install-node-and-npm</goal>
               </goals>
               <configuration>
-                <nodeVersion>v0.10.40</nodeVersion>
-                <npmVersion>2.12.1</npmVersion>
+                <nodeVersion>v8.9.4</nodeVersion>
```
Comment (esevastyanov) [inline pom.xml]: boost 💯

File: src/server/server.coffee (hunk 1 above)
Comment (clintropolis) [reply src/server/server.coffee]: afaict, yes, though it doesn't really seem necessary. It also is sort of racey since this doesn't block http server from starting, so there exists a period where it can accept http server requests but zk isn't initialized.

I'm getting ready to push another commit that updates some npm dependencies to their latest versions, and while I was fixing/moving stuff also moved http server start to happen after this dns resolution bit.

**Comment by egor-ryashin** [comment]
Cool, I've run smoke tests, works for both clusters :thumbsup:

**Comment by clintropolis** [comment]
Unit tests are fixed and now run as part of PR.

Fwiw, we have been running the built-in proxy server from this branch for over a week now to serve as druid console for both of our clusters without issue, I think it would be relatively safe to merge.

**Comment by vogievetsky** [comment]
I read through this in some detail and it looks good to me 👍  great work.

**Comment by gianm** [comment]
If it's good enough for @vogievetsky then it's good enough for me. Thanks @clintropolis!
